# Que 1

## Perform the One Hot Encoding separately on features *–degree_t*

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
df=pd.read_excel('Placement_Dataset.xlsx')

In [3]:
df.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [4]:
df.dtypes

sl_no               int64
gender             object
ssc_p             float64
ssc_b              object
hsc_p             float64
hsc_b              object
hsc_s              object
degree_p          float64
degree_t           object
workex             object
etest_p           float64
specialisation     object
mba_p             float64
status             object
salary            float64
dtype: object

In [5]:
df['degree_t'].unique()


array(['Sci&Tech', 'Comm&Mgmt', 'Others'], dtype=object)

In [6]:
df['hsc_s'].unique()

array(['Commerce', 'Science', 'Arts'], dtype=object)

In [7]:
ohe=OneHotEncoder()

In [8]:
print(ohe)

OneHotEncoder()


### fit_transform method to convert the output to an array.

In [9]:
ohe.fit_transform(df[['degree_t']]).toarray()

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0

In [10]:
feature_array=ohe.fit_transform(df[['degree_t']]).toarray()

In [11]:
feature_labels=ohe.categories_
feature_labels

[array(['Comm&Mgmt', 'Others', 'Sci&Tech'], dtype=object)]

In [12]:
feature_labels=np.array(feature_labels).ravel()
feature_labels

array(['Comm&Mgmt', 'Others', 'Sci&Tech'], dtype=object)

In [13]:
df1=pd.DataFrame(feature_array,columns=feature_labels)
df1

Comm&Mgmt  Others  Sci&Tech
0          0.0     0.0       1.0
1          0.0     0.0       1.0
2          1.0     0.0       0.0
3          0.0     0.0       1.0
4          1.0     0.0       0.0
..         ...     ...       ...
210        1.0     0.0       0.0
211        0.0     0.0       1.0
212        1.0     0.0       0.0
213        1.0     0.0       0.0
214        1.0     0.0       0.0

[215 rows x 3 columns]

In [14]:
df2=pd.concat([df,df1],axis=1)
df2

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
..     ...    ...    ...      ...    ...      ...       ...       ...   
210    211      M  80.60   Others  82.00   Others  Commerce     77.60   
211    212      M  58.00   Others  60.00   Others   Science     72.00   
212    213      M  67.00   Others  67.00   Others  Commerce     73.00   
213    214      F  74.00   Others  66.00   Others  Commerce     58.00   
214    215      M  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p      status    salary  \
0     Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0   
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0   
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0   
3     Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN   
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0   
..         ...    ...      ...            ...    ...         ...       ...   
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49      Placed  400000.0   
211   Sci&Tech     No     74.0        Mkt&Fin  53.62      Placed  275000.0   
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0   
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23      Placed  204000.0   
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  Not Placed       NaN   

     Comm&Mgmt  Others  Sci&Tech  
0          0.0     0.0       1.0  
1          0.0     0.0       1.0  
2          1.0     0.0       0.0  
3          0.0     0.0       1.0  
4          1.0     0.0       0.0  
..         ...     ...       ...  
210        1.0     0.0       0.0  
211        0.0     0.0       1.0  
212        1.0     0.0       0.0  
213        1.0     0.0       0.0  
214        1.0     0.0       0.0  

[215 rows x 18 columns]

### Perform the One Hot Encoding separately on features *-hsc_s*

In [15]:
df['hsc_s'].unique()

array(['Commerce', 'Science', 'Arts'], dtype=object)

In [16]:
ohe.fit_transform(df[['hsc_s']]).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1

In [17]:
feature_array=ohe.fit_transform(df[['hsc_s']]).toarray()

In [18]:
feature_labels=ohe.categories_
feature_labels

[array(['Arts', 'Commerce', 'Science'], dtype=object)]

In [19]:
feature_labels=np.array(feature_labels).ravel()
feature_labels

array(['Arts', 'Commerce', 'Science'], dtype=object)

In [20]:
df1=pd.DataFrame(feature_array,columns=feature_labels)
df1

Arts  Commerce  Science
0     0.0       1.0      0.0
1     0.0       0.0      1.0
2     1.0       0.0      0.0
3     0.0       0.0      1.0
4     0.0       1.0      0.0
..    ...       ...      ...
210   0.0       1.0      0.0
211   0.0       0.0      1.0
212   0.0       1.0      0.0
213   0.0       1.0      0.0
214   0.0       0.0      1.0

[215 rows x 3 columns]

In [21]:
df3=pd.concat([df,df1],axis=1)
df3

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
..     ...    ...    ...      ...    ...      ...       ...       ...   
210    211      M  80.60   Others  82.00   Others  Commerce     77.60   
211    212      M  58.00   Others  60.00   Others   Science     72.00   
212    213      M  67.00   Others  67.00   Others  Commerce     73.00   
213    214      F  74.00   Others  66.00   Others  Commerce     58.00   
214    215      M  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p      status    salary  \
0     Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0   
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0   
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0   
3     Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN   
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0   
..         ...    ...      ...            ...    ...         ...       ...   
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49      Placed  400000.0   
211   Sci&Tech     No     74.0        Mkt&Fin  53.62      Placed  275000.0   
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0   
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23      Placed  204000.0   
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  Not Placed       NaN   

     Arts  Commerce  Science  
0     0.0       1.0      0.0  
1     0.0       0.0      1.0  
2     1.0       0.0      0.0  
3     0.0       0.0      1.0  
4     0.0       1.0      0.0  
..    ...       ...      ...  
210   0.0       1.0      0.0  
211   0.0       0.0      1.0  
212   0.0       1.0      0.0  
213   0.0       1.0      0.0  
214   0.0       0.0      1.0  

[215 rows x 18 columns]

# Que 2

##  Perform the One Hot Label separately on features –status

In [22]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [23]:
df=pd.read_excel('Placement_Dataset.xlsx')
df.head(10)

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   
5      6      M  55.00   Others  49.80   Others   Science     67.25   
6      7      F  46.00   Others  49.20   Others  Commerce     79.00   
7      8      M  82.00  Central  64.00  Central   Science     66.00   
8      9      M  73.00  Central  79.00  Central  Commerce     72.00   
9     10      M  58.00  Central  70.00  Central  Commerce     61.00   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No    55.00         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes    86.50        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No    75.00        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No    66.00         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No    96.80        Mkt&Fin  55.50      Placed  425000.0  
5   Sci&Tech    Yes    55.00        Mkt&Fin  51.58  Not Placed       NaN  
6  Comm&Mgmt     No    74.28        Mkt&Fin  53.29  Not Placed       NaN  
7   Sci&Tech    Yes    67.00        Mkt&Fin  62.14      Placed  252000.0  
8  Comm&Mgmt     No    91.34        Mkt&Fin  61.29      Placed  231000.0  
9  Comm&Mgmt     No    54.00        Mkt&Fin  52.21  Not Placed       NaN

In [24]:
le=LabelEncoder()

In [25]:
print(le)

LabelEncoder()


In [26]:
encoded_label=le.fit_transform(df[['status']])
encoded_label

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [27]:
print("Original_categories",df[['status']])
print("Encoded_label",encoded_label)

Original_categories          status
0        Placed
1        Placed
2        Placed
3    Not Placed
4        Placed
..          ...
210      Placed
211      Placed
212      Placed
213      Placed
214  Not Placed

[215 rows x 1 columns]
Encoded_label [1 1 1 0 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0
 1 1 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1
 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1 0 0 1 1 0 1
 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 0 1 0 1 1 1 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 0
 1 0 1 0 0 0 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 0]
